#!/bin/bash
# THIS SCRIPT COMPUTES THE LOADPATH and other useful Coq flags
# for users of VST.
#
# USAGE:
#   coqc `my/path/to/vst/coqflags` myfile.v
#   coqide `my/path/to/vst/coqflags` myfile.v &
#
# Suppose you have myfile.v that contains "Require Import VST.floyd.proofauto."
# or contains "Require Import Clightdefs."  To compile your .v file
# with coqc, or to edit it with CoqIDE or Proof General,
# you will need a loadpath to access proofauto and Clightdefs.
# Suppose VST is installed in your file system at some pathname
# (shown here as my/path/to/vst, but the pathname could be as simple as ".").
# Then execute   my/path/to/vst/coqflags   to compute the loadpath.
#
# TO INCLUDE EXTRA COMPONENTS OF VST
# use extra arguments, e.g.,
#   coqc `my/path/to/vst/coqflags concurrency` myfile.v
#
# TO INCLUDE EXTRA COMPONENTS OF YOUR OWN PROJECT
#  assuming your project is NOT within the VST directory,
# use extra directives separate from the coqflags utility, e.g.,
#   coqc `my/path/to/vst/coqflags` -Q some/thing Thing myfile.v


VST=`dirname $0`
DIRS="msl sepcomp veric floyd $*"

if [ -v WINDIR ]  # hacks necessary for cygwin
then
VST=`(cd $VST; /usr/bin/pwd)| awk '/^[/]cygdrive[/]/{sub(/^[/]cygdrive[/]/,""); sub("/",":/"); print $0}'`
FLAGS="-async-proofs off"
else
FLAGS=
fi

for D in $DIRS
do
    FLAGS=$FLAGS" -Q $VST/$D VST.$D"
done    
    

echo $FLAGS -R $VST/compcert compcert
