#!/bin/bash

EXTRA="wand_demo sha fcf hmacfcf tweetnacl20140427 hmacdrbg aes mailbox"
FLAGS=""
for D in $EXTRA
do 
 FLAGS=$FLAGS" -Q $D $D"
done
coqide `./coqflags concurrency ccc26x86` $FLAGS -R mathcomp mathcomp $* &
