
VC.pdf: VC.tex book.aux lstlangcoq.sty macros.tex setup.tex mathpartir.sty overlay.sty
	pdflatex VC; pdflatex VC


VerifiableC.pdf: VerifiableC.tex book.aux lstlangcoq.sty macros.tex setup.tex mathpartir.sty overlay.sty
	pdflatex VerifiableC; pdflatex VerifiableC
