#!/usr/bin/env bash

MAKE=${MAKE:-make}

if [ "$#" -eq 0 ]; then
	echo "Usage: $0 <a list of make-targets>..." >&2
	exit 0
fi

# run make -Bn for all provided targets ("$@" preserves separate args)
${MAKE} CLIGHTGEN="CLIGHTGEN" -Bn "$@" 2>/dev/null | \
 awk '/^echo COQC /{print $NF}/^CLIGHTGEN/{print $NF}'
