#!/bin/sh
echo >version.v 'Require Import String. Open Scope string.'
echo -n >>version.v 'Definition svn_rev := "'
svnversion -n >>version.v
echo >>version.v '".'
echo -n >>version.v 'Definition release := "'
tr -d '[:cntrl:]' <VERSION >>version.v
echo >>version.v '".'
echo -n >>version.v 'Definition date := "'
date --rfc-3339=date | tr -d '[:cntrl:]' >>version.v
echo >>version.v '".'
