all :
	cd lam_ref; make
#	cd imp; make
	cd funclistmach; make
	cd funclistmach2; make
	cd hoare; make
	cd sep; make
	cd cont; make
	cd floyd_tut; make

clean :
	cd lam_ref; make clean
	cd imp; make clean
	cd funclistmach; make clean
	cd funclistmach2; make clean
	cd hoare; make clean
	cd sep; make clean
	cd cont; make clean

docs :
	cd lam_ref; make docs
	cd imp; make docs
	cd funclistmach; make docs
	cd funclistmach2; make docs
	cd hoare; make docs
	cd sep; make docs
	cd cont; make docs

.PHONY : all clean docs
