all :
	cd lam_ref; make
	cd imp; make
	cd funclistmach; make
	cd funclistmach2; make

clean :
	cd lam_ref; make clean
	cd imp; make clean
	cd funclistmach; make clean
	cd funclistmach2; make clean

docs :
	cd lam_ref; make docs
	cd imp; make docs
	cd funclistmach; make docs
	cd funclistmach2; make docs

.PHONY : all clean docs
