install:
	install -d $(INSTALLDIR)/lithium
	install -d $(INSTALLDIR)/typing
	install -d $(INSTALLDIR)/typing/automation
	install -m 0644 lithium/*.v $(INSTALLDIR)/lithium
	install -m 0644 lithium/*.vo $(INSTALLDIR)/lithium
	install -m 0644 typing/*.v $(INSTALLDIR)/typing
	install -m 0644 typing/*.vo $(INSTALLDIR)/typing
	install -m 0644 typing/automation/*.v $(INSTALLDIR)/typing/automation
	install -m 0644 typing/automation/*.vo $(INSTALLDIR)/typing/automation